[package]
name = "r8"
version = "0.1.0"
edition = "2018"

[dependencies]
lazy_static = "1.1.0"
regex = "1.0.5"
error-chain = "0.12.0"
matches = "0.1.8"
maplit = "1.0.1"
stdweb = "0.4.9"
serde = "1.0.79"
serde_derive = "1.0.79"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
